export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const FILTER_MOVIES_BY_TITLE = "FILTER_MOVIES_BY_TITLE"
export const FILTER_MOVIES_BY_RATE = "FILTER_MOVIES_BY_RATE"
export const DISPLAY_MOVIES = "DISPLAY_MOVIES"